-- Demo seed data for a live presentation. Realistic-looking scholarships,
-- housing listings, and one in-progress visa checklist for the signed-in
-- test account, so Home/Explore/Journey are never empty screens.

INSERT INTO opportunities (type, title, description, country, institution, field_of_study, funding_amount, currency, eligibility, application_url, deadline, sponsors_visa, is_verified, verified_at) VALUES
('scholarship', 'Vanier Canada Graduate Scholarship', 'Full funding for doctoral students demonstrating leadership and academic excellence across all fields of study.', 'Canada', 'Government of Canada', 'All fields', 50000, 'CAD', 'PhD applicants, first year of doctoral study, nominated by host institution.', 'https://vanier.gc.ca', CURRENT_DATE + INTERVAL '21 days', true, true, now()),
('scholarship', 'Chevening Scholarship', 'UK government''s global scholarship programme funding one-year master''s degrees.', 'United Kingdom', 'UK Government', 'All fields', 18000, 'GBP', 'Bachelor''s degree, 2+ years work experience, return to home country after study.', 'https://chevening.org', CURRENT_DATE + INTERVAL '45 days', true, true, now()),
('grant', 'DAAD Study Scholarship', 'Funding for international students pursuing a master''s degree at German universities.', 'Germany', 'DAAD', 'Engineering & Sciences', 12000, 'EUR', 'Bachelor''s degree with above-average results, proficiency in German or English.', 'https://daad.de', CURRENT_DATE + INTERVAL '10 days', true, true, now()),
('fellowship', 'Fulbright Foreign Student Program', 'Funding for graduate study, research, or teaching in the United States.', 'United States', 'Fulbright Commission', 'All fields', 40000, 'USD', 'Bachelor''s degree, strong academic record, English proficiency.', 'https://foreign.fulbrightonline.org', CURRENT_DATE + INTERVAL '60 days', true, true, now()),
('scholarship', 'Australia Awards Scholarship', 'Long-term development scholarships for postgraduate study in Australia.', 'Australia', 'Australian Government', 'Development-related fields', 35000, 'AUD', 'Citizen of an eligible developing country, no other citizenship or permanent residency in Australia.', 'https://australiaawards.gov.au', CURRENT_DATE + INTERVAL '30 days', true, false, NULL),
('internship', 'Google Africa Internship Programme', 'Paid summer internship for students studying computer science or related fields.', 'Ghana', 'Google', 'Computer Science', NULL, NULL, 'Currently enrolled in an undergraduate or graduate program.', 'https://careers.google.com', CURRENT_DATE + INTERVAL '15 days', false, true, now()),
('scholarship', 'Erasmus Mundus Joint Master Degrees', 'Fully-funded joint master''s programmes delivered by a consortium of European universities.', 'Netherlands', 'European Commission', 'All fields', 24000, 'EUR', 'Bachelor''s degree, competitive selection across the consortium.', 'https://erasmus-plus.ec.europa.eu', CURRENT_DATE + INTERVAL '50 days', true, true, now()),
('scholarship', 'Swiss Government Excellence Scholarship', 'Funding for postgraduate research and doctoral studies at Swiss universities.', 'Switzerland', 'Swiss Confederation', 'All fields', 30000, 'CHF', 'Master''s degree, nomination by home country''s government or university.', 'https://www.sbfi.admin.ch', CURRENT_DATE + INTERVAL '40 days', true, true, now()),
('grant', 'MEXT Japanese Government Scholarship', 'Covers tuition, a monthly stipend and airfare for study at a Japanese university.', 'Japan', 'MEXT', 'All fields', 15000, 'USD', 'Under 35, nominated via embassy or university recommendation.', 'https://www.studyinjapan.go.jp', CURRENT_DATE + INTERVAL '55 days', true, true, now()),
('scholarship', 'New Zealand ASEAN Scholar Awards', 'Funds undergraduate and postgraduate study in New Zealand for ASEAN nationals.', 'New Zealand', 'New Zealand Government', 'Development-related fields', 28000, 'NZD', 'Citizen of an ASEAN member country, meets academic entry requirements.', 'https://www.mfat.govt.nz', CURRENT_DATE + INTERVAL '38 days', true, false, NULL),
('fellowship', 'Mastercard Foundation Scholars Program', 'Comprehensive scholarships and leadership development for African students.', 'Rwanda', 'Mastercard Foundation', 'All fields', 20000, 'USD', 'African citizen, demonstrated financial need, strong academic record.', 'https://mastercardfdn.org', CURRENT_DATE + INTERVAL '25 days', true, true, now()),
('internship', 'Microsoft LEAP Engineering Program', 'Apprenticeship-style program for non-traditional software engineers to build industry skills.', 'United States', 'Microsoft', 'Computer Science', NULL, NULL, 'Self-taught or bootcamp background welcome, no CS degree required.', 'https://careers.microsoft.com', CURRENT_DATE + INTERVAL '18 days', true, true, now()),
('scholarship', 'Holland Scholarship', 'Scholarship for non-EEA students beginning a bachelor''s or master''s in the Netherlands.', 'Netherlands', 'Dutch Ministry of Education', 'All fields', 5000, 'EUR', 'Non-EEA nationality, admitted to a participating Dutch institution.', 'https://www.studyinholland.nl', CURRENT_DATE + INTERVAL '33 days', true, true, now()),
('grant', 'Commonwealth Shared Scholarship', 'Master''s-level funding for students from developing Commonwealth countries.', 'United Kingdom', 'Commonwealth Scholarship Commission', 'Development-related fields', 16000, 'GBP', 'Commonwealth citizen, resident in a developing Commonwealth country.', 'https://cscuk.fcdo.gov.uk', CURRENT_DATE + INTERVAL '48 days', true, true, now()),
('scholarship', 'Korean Government Scholarship Program', 'Fully-funded undergraduate and graduate study at Korean universities, including Korean language training.', 'South Korea', 'NIIED', 'All fields', 14000, 'USD', 'Under 25 (undergraduate) or under 40 (graduate), nominated by embassy.', 'https://www.studyinkorea.go.kr', CURRENT_DATE + INTERVAL '42 days', true, true, now()),
('fellowship', 'Rhodes Scholarship', 'Postgraduate study at the University of Oxford for exceptional students worldwide.', 'United Kingdom', 'Rhodes Trust', 'All fields', 45000, 'GBP', 'Outstanding academic achievement, leadership, and service to others.', 'https://www.rhodeshouse.ox.ac.uk', CURRENT_DATE + INTERVAL '65 days', true, true, now()),
('internship', 'UN Young Professionals Programme', 'Entry point into a career at the United Nations for early-career professionals.', 'Switzerland', 'United Nations', 'Public Policy', NULL, NULL, 'Under 32, relevant advanced degree, fluency in English or French.', 'https://careers.un.org', CURRENT_DATE + INTERVAL '28 days', false, true, now()),
('scholarship', 'Turkiye Burslari Scholarship', 'Fully-funded scholarships covering all levels of study at Turkish universities.', 'Turkey', 'Turkish Government', 'All fields', 10000, 'USD', 'Strong academic record, under age limits per study level.', 'https://www.turkiyeburslari.gov.tr', CURRENT_DATE + INTERVAL '36 days', true, true, now()),
('grant', 'Endeavour Leadership Program', 'Australian government funding for leadership development through study, research or professional development.', 'Australia', 'Australian Government', 'All fields', 27000, 'AUD', 'Citizen of an eligible country, demonstrated leadership potential.', 'https://internationaleducation.gov.au', CURRENT_DATE + INTERVAL '52 days', true, false, NULL);

INSERT INTO housing_listings (title, description, city, country, address, rent_amount, currency, rent_period, bedrooms, bathrooms, furnished, near_university, status, rating) VALUES
('Bright studio near downtown campus', 'Renovated studio apartment, 10 minute walk to campus, all utilities included.', 'Toronto', 'Canada', '145 College St', 1450, 'CAD', 'month', 1, 1, true, 'University of Toronto', 'active', 4.6),
('Shared 2-bed apartment, student-friendly', 'Furnished room in a 2-bedroom apartment shared with one other student.', 'Manchester', 'United Kingdom', '22 Oxford Rd', 650, 'GBP', 'month', 1, 1, true, 'University of Manchester', 'active', 4.2),
('Cozy 1-bed close to transit', 'Quiet neighbourhood, direct bus line to the main campus, kitchen fully equipped.', 'Berlin', 'Germany', 'Karl-Marx-Allee 90', 780, 'EUR', 'month', 1, 1, false, 'Humboldt University', 'active', 4.4),
('Modern shared house, 4 rooms available', 'Newly built student house, high-speed internet, laundry on site.', 'Boston', 'United States', '412 Beacon St', 1200, 'USD', 'month', 1, 2, true, 'Boston University', 'active', 4.8),
('Sunny room in shared flat', 'Bright private room in a 3-bedroom flat, shared kitchen and living room, bike storage.', 'Amsterdam', 'Netherlands', 'Prinsengracht 210', 890, 'EUR', 'month', 1, 1, true, 'University of Amsterdam', 'active', 4.5),
('Compact studio, walk to campus', 'Efficient studio with kitchenette, ideal for a single student, laundry in building.', 'Sydney', 'Australia', '58 King St', 1650, 'AUD', 'month', 1, 1, true, 'University of Sydney', 'active', 4.3),
('Quiet 1-bed near tech park', 'Renovated one-bedroom apartment, 15 minutes by bike to the main university campus.', 'Seoul', 'South Korea', '12 Sinchon-ro', 720000, 'KRW', 'month', 1, 1, true, 'Yonsei University', 'active', 4.6),
('Shared apartment, 3 rooms available', 'Well-connected apartment near the metro, international student community.', 'Paris', 'France', '18 Rue Mouffetard', 700, 'EUR', 'month', 1, 1, false, 'Sorbonne University', 'active', 4.1),
('Furnished room with private bath', 'Recently renovated home with 24-hour security, close to public transit.', 'Dublin', 'Ireland', '4 Rathmines Rd', 950, 'EUR', 'month', 1, 1, true, 'Trinity College Dublin', 'active', 4.4),
('Budget shared room near campus', 'Affordable shared accommodation, popular with exchange students, all bills included.', 'Kuala Lumpur', 'Malaysia', '33 Jalan Universiti', 450, 'MYR', 'month', 1, 1, true, 'University of Malaya', 'active', 4.0),
('Modern 1-bed apartment', 'New-build apartment with gym access, 10 minute walk to the business school.', 'Singapore', 'Singapore', '88 Clementi Rd', 1900, 'SGD', 'month', 1, 1, true, 'National University of Singapore', 'active', 4.7),
('Cozy room in family home', 'Homestay room with meals included, great for first-time international students.', 'Auckland', 'New Zealand', '21 Symonds St', 380, 'NZD', 'week', 1, 1, true, 'University of Auckland', 'active', 4.5),
('Shared house near medical campus', 'Five-bedroom house shared with graduate students, garden and parking included.', 'Cape Town', 'South Africa', '9 Main Rd', 4200, 'ZAR', 'month', 1, 2, false, 'University of Cape Town', 'active', 4.2);

INSERT INTO visa_checklists (user_id, origin_country, destination_country, visa_type, items, completed_items) VALUES
('9aa43851-bd4e-4ba6-9460-69bcb8e9c1ed', 'Ghana', 'Canada', 'Study Permit',
 '[
   {"id":"acceptance-letter","title":"Get a letter of acceptance from a designated learning institution"},
   {"id":"proof-of-funds","title":"Show proof of funds (tuition + living costs)"},
   {"id":"gic","title":"Purchase a Guaranteed Investment Certificate (GIC)"},
   {"id":"medical-exam","title":"Complete an upfront medical exam"},
   {"id":"biometrics","title":"Give biometrics (fingerprints and photo)"},
   {"id":"application-submit","title":"Submit the study permit application online"},
   {"id":"passport-valid","title":"Ensure passport is valid for the full duration of study"},
   {"id":"language-test","title":"Take an English or French proficiency test"}
 ]'::jsonb,
 ARRAY['acceptance-letter','proof-of-funds']);
