import { query } from "../../db";
import { dispatchNotification } from "../push";
import { routes } from "../deep-links";
import { claimReminder, completeReminder } from "./store";
import type { PassStats } from "./types";

/**
 * Visa checklist nudges.
 *
 * ── Why this is a nudge and not a deadline reminder ───────────────────────
 * §3.7 asks for reminders on `visa_checklists` items. The data cannot support
 * that, and it is worth being exact about why rather than approximating it.
 *
 * A checklist row's `items` are roadmap phases generated by the Visa Roadmap
 * feature. A phase looks like:
 *
 *     { id, title, timeframe: "Weeks 1–3", cost: "$150–$500", documents, tip }
 *
 * `timeframe` is a relative estimate the model produced — "weeks 1 to 3" of a
 * journey with no fixed start — and there is no due date anywhere in the
 * structure. Turning "Weeks 1–3" into a calendar date would mean picking a
 * start (creation date? intake date we do not have?) and then pushing a
 * notification that asserts a deadline we invented. That is precisely what the
 * AI safety contract forbids, and a fabricated visa deadline is worse coming
 * from a push notification than from a chat reply, because the user cannot see
 * the reasoning behind it.
 *
 * So what fires here is about the user's own inactivity, which is a fact we
 * actually hold: a checklist with unfinished phases that has not been touched
 * in two weeks. It never claims anything is due.
 *
 * ── To make real item deadlines work ──────────────────────────────────────
 * Add an optional `due_date` to the phase schema and let the user set it when
 * they tick through the roadmap — a date the *user* chose, not one we derived.
 * That path is not built here because nothing writes such a field today, and
 * shipping a branch no data can reach is dead code that reads as a feature.
 */

/** Days of no activity before a single, one-off nudge. */
const STALE_AFTER_DAYS = 14;

type StaleRow = {
  checklist_id: string;
  user_id: string;
  destination_country: string;
  total_items: number;
  completed_items: number;
};

/**
 * Checklists that went quiet.
 *
 * Bounded by the pass window on the *upper* side only: a checklist that crossed
 * the staleness line while the scheduler was down should still get its nudge,
 * because unlike a session reminder it is not tied to a moment that has passed.
 */
async function staleChecklists(windowEnd: Date, limit: number) {
  return query<StaleRow>(
    `SELECT c.id                          AS checklist_id,
            c.user_id,
            c.destination_country,
            jsonb_array_length(c.items)   AS total_items,
            COALESCE(array_length(c.completed_items, 1), 0) AS completed_items
       FROM visa_checklists c
       JOIN users u ON u.id = c.user_id
      WHERE COALESCE(c.updated_at, c.created_at) < $1::timestamptz - ($2 || ' days')::interval
        AND jsonb_typeof(c.items) = 'array'
        -- Nothing to nudge about if they have finished it.
        AND COALESCE(array_length(c.completed_items, 1), 0) < jsonb_array_length(c.items)
      ORDER BY c.created_at ASC
      LIMIT $3`,
    [windowEnd, String(STALE_AFTER_DAYS), limit],
  );
}

export async function runChecklistReminders(
  windowEnd: Date,
  stats: PassStats,
  limit = 500,
): Promise<void> {
  let rows: StaleRow[];
  try {
    rows = await staleChecklists(windowEnd, limit);
  } catch (err) {
    console.error("[reminders] checklist query failed:", (err as Error).message);
    stats.errors++;
    return;
  }

  for (const row of rows) {
    // One nudge per checklist, ever. The fire key carries no date bucket on
    // purpose: a recurring reminder about a list someone has stopped using is
    // nagging, and this audience has every reason to keep notifications on for
    // the alerts that matter. Regenerating a roadmap creates a new row, which
    // legitimately earns a fresh nudge.
    const claim = await claimReminder({
      kind: "checklist_stale",
      subjectId: row.checklist_id,
      userId: row.user_id,
      fireKey: `stale-${STALE_AFTER_DAYS}d`,
      dueAt: null,
    });
    if (!claim) {
      stats.skippedAlreadySent++;
      continue;
    }

    await dispatchNotification({
      userId: row.user_id,
      // `info`, not `deadline`. Nothing here is due; miscategorising it would
      // give it the never-collapse, high-priority delivery that real deadlines
      // get, and dilute the category the user relies on.
      kind: "info",
      titleKey: "notification.checklist.title",
      bodyKey: "notification.checklist.body",
      vars: {
        destination: row.destination_country,
        remaining: String(Math.max(0, row.total_items - row.completed_items)),
      },
      deepLink: routes.roadmap(),
      data: { checklistId: row.checklist_id },
      collapseKey: `checklist:${row.checklist_id}`,
    });

    await completeReminder(claim);
    stats.sent++;
  }
}
